# Generated by Django 5.2.1 on 2025-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='generation_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
