# Generated by Django 5.2.1 on 2025-06-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_nation_generation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nation',
            options={},
        ),
        migrations.AddField(
            model_name='nation',
            name='expanded_description',
            field=models.TextField(blank=True, help_text='The AI-expanded, detailed design document for the nation.', null=True),
        ),
        migrations.AddField(
            model_name='nation',
            name='generated_mod_code',
            field=models.TextField(blank=True, help_text='The accumulating .dm mod code generated at each step.', null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nation',
            name='description',
            field=models.TextField(default=1, help_text='A brief, high-level description or idea for the nation.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nation',
            name='generation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('prompt_expansion', 'Step 1: Expanding Prompt'), ('nation_details', 'Step 2: Nation Details'), ('commanders', 'Step 3: Commanders'), ('troops', 'Step 4: Troops'), ('weapons', 'Step 5: Weapons'), ('armor', 'Step 6: Armor'), ('spells', 'Step 7: Spells'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='The current stage of the mod generation process.', max_length=20),
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
