# Generated by Django 5.2.1 on 2025-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0003_alter_nation_options_nation_expanded_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='generation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('prompt_expansion', 'Step 1: Expanding Concept'), ('nation_details', 'Step 2: Nation Details & Tags'), ('commanders', 'Step 3: Commanders'), ('troops', 'Step 4: Troops'), ('heroes', 'Step 5: National Heroes'), ('spells', 'Step 6: National Spells'), ('items', 'Step 7: Weapons & Armor'), ('validation', 'Step 8: Final Validation'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='The current stage of the mod generation process.', max_length=20),
        ),
    ]
