# Generated by Django 5.2.1 on 2025-07-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0004_alter_nation_generation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='last_validation_report',
            field=models.TextField(blank=True, help_text='The report from the last validation attempt, if errors were found.', null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='generation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('prompt_expansion', 'Step 1: Expanding Concept'), ('nation_details', 'Step 2: Nation Details & Tags'), ('commanders', 'Step 3: Commanders'), ('troops', 'Step 4: Troops'), ('heroes', 'Step 5: National Heroes'), ('spells', 'Step 6: National Spells'), ('items', 'Step 7: Weapons & Armor'), ('validation', 'Step 8: Final Validation'), ('fixing_errors', 'Step 9: Applying Fixes'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='The current stage of the mod generation process.', max_length=20),
        ),
    ]
