# Generated by Django 5.2.1 on 2025-06-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('MagicSites', 'Magic Site'), ('Mercenary', 'Mercenary'), ('afflictions', 'Affliction'), ('anon_province_events', 'Anonymous Province Event'), ('armors', 'Armor'), ('attribute_keys', 'Attribute Key'), ('attributes_by_armor', 'Attributes by Armor'), ('attributes_by_nation', 'Attributes by Nation'), ('attributes_by_spell', 'Attributes by Spell'), ('attributes_by_weapon', 'Attributes by Weapon'), ('buffs_1_types', 'Buff Type 1'), ('buffs_2_types', 'Buff Type 2'), ('coast_leader_types_by_nation', 'Coast Leader'), ('coast_troop_types_by_nation', 'Coast Troop'), ('effect_modifier_bits', 'Effect Modifier Bit'), ('effects_info', 'Effect Info'), ('effects_spells', 'Effect Spell'), ('effects_weapons', 'Effect Weapon'), ('enchantments', 'Enchantment'), ('events', 'Event'), ('fort_leader_types_by_nation', 'Fort Leader'), ('fort_troop_types_by_nation', 'Fort Troop'), ('item', 'Item'), ('magic_paths', 'Magic Path'), ('map_terrain_types', 'Map Terrain Type'), ('monster_tags', 'Monster Tag'), ('nametypes', 'Name Type'), ('nations', 'Nation'), ('nonfort_leader_types_by_nation', 'Non-Fort Leader'), ('nonfort_troop_types_by_nation', 'Non-Fort Troop'), ('other_planes', 'Other Plane'), ('pretender_types_by_nation', 'Pretender Type'), ('protections_by_armor', 'Protections by Armor'), ('realms', 'Realm'), ('site_terrain_types', 'Site Terrain Type'), ('special_damage_types', 'Special Damage Type'), ('special_unique_summons', 'Special Unique Summon'), ('spell', 'Spell'), ('terrain_specific_summons', 'Terrain Specific Summon'), ('unit', 'Unit'), ('unit_effects', 'Unit Effect'), ('unpretender_types_by_nation', 'Unpretender Type'), ('weapons', 'Weapon')], db_index=True, max_length=50)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('attributes', models.JSONField(help_text='All other attributes from the JSONL file.')),
                ('reference_text', models.TextField(help_text='Pre-formatted text for the AI prompt')),
            ],
            options={
                'ordering': ['entity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the mod example.', max_length=100, unique=True)),
                ('mod_text', models.TextField(help_text='The full text content of the .dm file.')),
            ],
        ),
    ]
