# Generated by Django 5.2.1 on 2025-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('unit', 'Unit'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('spell', 'Spell'), ('site', 'Magic Site')], db_index=True, max_length=20)),
                ('entity_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('attributes', models.JSONField(help_text='All other attributes from the JSONL file.')),
                ('reference_text', models.TextField(help_text='Pre-formatted text for the AI prompt')),
            ],
            options={
                'ordering': ['entity_type', 'name'],
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
