# Generated by Django 5.2.1 on 2025-06-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_alter_gameentity_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the mod example.', max_length=100, unique=True)),
                ('mod_text', models.TextField(help_text='The full text content of the .dm file.')),
            ],
        ),
    ]
