# Generated by Django 5.2 on 2025-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='generated_dm_code',
            field=models.TextField(blank=True, help_text='The generated Dominions 6 mod code.', null=True),
        ),
        migrations.AddField(
            model_name='nation',
            name='generation_error',
            field=models.TextField(blank=True, help_text='Error message if the last generation failed.', null=True),
        ),
        migrations.AddField(
            model_name='nation',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('NONE', 'None')], default='NONE', help_text='Status of the last DM code generation task.', max_length=15),
        ),
        migrations.AddField(
            model_name='nation',
            name='generation_task_id',
            field=models.CharField(blank=True, editable=False, help_text='Celery Task ID for the last generation attempt.', max_length=50, null=True),
        ),
    ]
